const movieSerie = [
  {
    title: "The Diparted",
    year: 2006,
    genre: "drammatico",
    rating: 4,
    type: "movie",
  },
  {
    title: "The Godfather",
    year: 1972,
    genre: "drammatico",
    rating: 4.5,
    type: "movie",
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    genre: "drammatico",
    rating: 4.7,
    type: "movie",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    genre: "drammatico",
    rating: 4.6,
    type: "movie",
  },
  {
    title: "The Silence of the Lambs",
    year: 1991,
    genre: "thriller",
    rating: 4.4,
    type: "movie",
  },
  {
    title: "Friends",
    year: 1994,
    genre: "sitcom",
    rating: 4.3,
    type: "serie",
    seasons: 10,
  },
  {
    title: "The Big Bang Theory",
    year: 2007,
    genre: "sitcom",
    rating: 4.1,
    type: "serie",
    seasons: 12,
  },
  {
    title: "Breaking Bad",
    year: 2008,
    genre: "drammatico",
    rating: 4.8,
    type: "serie",
    seasons: 5,
  },
  {
    title: "Game of Thrones",
    year: 2011,
    genre: "fantasy",
    rating: 4.4,
    type: "serie",
    seasons: 8,
  },
  {
    title: "The Office",
    year: 2005,
    genre: "sitcom",
    rating: 4.2,
    type: "serie",
    seasons: 9,
  },
];

exports.movieSerie = movieSerie;
